AWSTemplateFormatVersion: '2010-09-09'
Description: Photo Album Infrastructure

Resources:

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: krisha-photoalbum-frontend-demo

  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: krisha-photoalbum-storage-demo